In [255]:
import numpy as np 
import pandas as pandas
from matplotlib import pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [256]:
dataLabel = pandas.read_csv("dummyDatasetProjectLabel.csv")
dataLabel

Marks
0      12
1       0
2      16
3      20
4      18
5       7
6      27
7      21
8      29
9       8
10     20
11     25
12     20
13     30
14     14
15      7
16     29
17      4
18      9
19      1

In [257]:
dataSupplied = pandas.read_csv("dummyDatasetProject.csv")
dataSupplied

Level
0   Intermediate
1       Beginner
2   Intermediate
3   Intermediate
4   Intermediate
5       Beginner
6       Advanced
7       Advanced
8       Advanced
9       Beginner
10  Intermediate
11      Advanced
12      Advanced
13      Advanced
14  Intermediate
15      Beginner
16      Advanced
17      Beginner
18      Beginner
19      Beginner

In [258]:
from sklearn.model_selection import train_test_split
training_set,testing_set = train_test_split(dataSupplied,test_size=0.35,random_state=50)
training_set

Level
2   Intermediate
17      Beginner
10  Intermediate
12      Advanced
5       Beginner
6       Advanced
4   Intermediate
14  Intermediate
1       Beginner
13      Advanced
11      Advanced
0   Intermediate
16      Advanced

In [259]:
from sklearn.model_selection import train_test_split
training_set_label,testing_set_label = train_test_split(dataLabel,test_size=0.35,random_state=50)
training_set_label

Marks
2      16
17      4
10     20
12     20
5       7
6      27
4      18
14     14
1       0
13     30
11     25
0      12
16     29

In [260]:
vectorizer1 = CountVectorizer()
transformed_training_labels = vectorizer1.fit_transform(training_set_label)
transformed_training_labels

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [261]:
vectorizer = CountVectorizer()
training_set_transformed = vectorizer.fit_transform(training_set)
training_set_transformed

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [262]:
training_set_transformed.shape

(1, 1)

In [263]:
from sklearn.neighbors import KNeighborsClassifier 
regressor = KNeighborsClassifier(n_neighbors=1)
regressor.fit(training_set_transformed,transformed_training_labels)

C:\Users\91989\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [264]:
testing_set_transformed = vectorizer.fit_transform(testing_set)
testing_set_transformed

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [265]:
testing_label_transformed = vectorizer1.fit_transform(testing_set_label)
testing_label_transformed

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [266]:
testing_set_transformed.shape

(1, 1)

In [267]:
results = regressor.predict(testing_set_transformed)
results

array([<1x1 sparse matrix of type '<class 'numpy.int64'>'
       	with 1 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [268]:
results_array_standard = results[0].toarray().flatten()
results_array_standard

array([1], dtype=int64)

In [269]:
labels_array_standard = testing_label_transformed.toarray().flatten()
labels_array_standard

array([1], dtype=int64)

In [270]:
accuracy = accuracy_score(results_array_standard,labels_array_standard)
accuracy

1.0

In [271]:
dataValidationLabel = pandas.read_csv("projectdatasetlabel.csv")
dataValidationLabel

Marks
0      25
1      18
2       7
3      29
4      12
5      16
6      22
7       5
8      30
9      14
10     19
11      2

In [272]:
dataValidation = pandas.read_csv("projectlabel.csv")
dataValidation

Level
0       Advanced
1   Intermediate
2       Beginner
3       Advanced
4   Intermediate
5   Intermediate
6       Advanced
7       Beginner
8       Advanced
9   Intermediate
10  Intermediate
11      Beginner

In [273]:
vectorizer3 = CountVectorizer()
transformed_validation_data = vectorizer3.fit_transform(dataValidation)
transformed_validation_data

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [274]:
vectorizer4 = CountVectorizer() 
transformed_validation_label = vectorizer4.fit_transform(dataValidationLabel)
transformed_validation_label

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [275]:
validation_results = regressor.predict(transformed_validation_data)
validation_results

array([<1x1 sparse matrix of type '<class 'numpy.int64'>'
       	with 1 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [276]:
validation_data_array_standard = validation_results[0].toarray().flatten()
validation_data_array_standard

array([1], dtype=int64)

In [277]:
validation_label_transformed = transformed_validation_label.toarray().flatten()
validation_label_transformed

array([1], dtype=int64)

In [299]:
accuracy_validation = accuracy_score(validation_data_array_standard,validation_label_transformed)
accuracy_validation

1.0